language: node_js
node_js:
  - "11"
env:
  - IONIC_VERSION="4.10.2" ANDROID_SDK_VERSION="4333796" ANDROID_HOME="/opt/android-sdk" ANDROID_BUILD_TOOLS_VERSION="19.1.0" CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL="https://services.gradle.org/distributions/gradle-gradle-4.10.1-all.zip"
before_install:
  - chmod +x "./scripts/prepare-android-env.sh"
  - "./scripts/prepare-android-env.sh"
after_success:
  - "npm run android"