language: node_js
node_js:
  - "11"
env:
  - IONIC_VERSION="4.10.2" ANDROID_SDK_VERSION="4333796" ANDROID_HOME="/opt/android-sdk" ANDROID_BUILD_TOOLS_VERSION="26.1.1"
before_install:
  - chmod +x "./scripts/prepare-android-env.sh"
  - "./scripts/prepare-android-env.sh"
after_success:
  - export GRADLE_HOME=/usr/bin/gradle
  - export PATH=$PATH:$GRADLE_HOME/bin
  - "npm run android"